  lr: 0.01
  weight_decay: 0
  milestones: [10]
  clip_grad: 0
  max_epochs: 1000
  early_stop: 30

  pass_device: True

  model_args:
    num_nodes: 5298
    adj_path: "../data/adj.npz"
    input_dim: 2666
    output_dim: 11
    hidden_dim: 32
    node_embedding_dim: 16
    cheb_k: 1
    num_layers: 1
